apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
  labels: 
    name: pv001
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow001
  nfs: 
    path: /data/volumes/v1
    server: 192.168.50.17
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv002
  labels: 
    name: pv002
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow002
  nfs: 
    path: /data/volumes/v2
    server: 192.168.50.17
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv003
  labels: 
    name: pv003
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow003
  nfs: 
    path: /data/volumes/v3
    server: 192.168.50.17
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv004
  labels: 
    name: pv004
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow004
  nfs: 
    path: /data/volumes/v4
    server: 192.168.50.17
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv005
  labels: 
    name: pv005
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow005
  nfs: 
    path: /data/volumes/v5
    server: 192.168.50.17
