server:
  port: 8086

spring:
  #数据库连接配置
  datasource:
    url: jdbc:mysql://127.0.0.1:8806/search?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 2
      min-idle: 1
      max-active: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validationQuery: select 'x'
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

mybatis:
  #类别名包的位置
  type-aliases-package: org.saxing.a0023_search.domain.entity
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: true
    mapUnderscoreToCamelCase: true
    #打印myBatis的sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
